# .yaml config file
#
# The PID gains and controller settings must be saved in a yaml file that gets loaded
# to the param server via the roslaunch file (monoped_control.launch).

pickbot:
  # Publish all joint states -----------------------------------
  # Creates the /joint_states topic necessary in ROS
  joint_state_controller:
    type: joint_state_controller/JointStateController
    # publish_rate: 1000
    publish_rate: 25

  # Effort Controllers ---------------------------------------
  joint1_position_controller:
    type: effort_controllers/JointPositionController
    joint: shoulder_pan_joint
    pid: {p: 10000, d: 150, i: 0, i_clamp: 1}
    #pid: {p: 50.0, i: 0.1, d: 0.0}

  joint2_position_controller:
    type: effort_controllers/JointPositionController
    joint: shoulder_lift_joint
    pid: {p: 50000, d: 150, i: 10, i_clamp: 50}
    #pid: {p: 50.0, i: 0.1, d: 0.0}

  joint3_position_controller:
    type: effort_controllers/JointPositionController
    joint: elbow_joint
    pid: {p: 50000, d: 150, i: 1, i_clamp: 25}
    #pid: {p: 50.0, i: 0.1, d: 0.0}

  joint4_position_controller:
    type: effort_controllers/JointPositionController
    joint: wrist_1_joint
    pid: {p: 100, d: 5, i: 0, i_clamp: 1}
    #pid: {p: 50.0, i: 0.1, d: 0.0}

  joint5_position_controller:
    type: effort_controllers/JointPositionController
    joint: wrist_2_joint
    pid: {p: 75, d: 2, i: 0, i_clamp: 1}
    #pid: {p: 50.0, i: 0.1, d: 0.0}

  joint6_position_controller:
    type: effort_controllers/JointPositionController
    joint: wrist_3_joint
    pid: {p: 25, d: 1, i: 0, i_clamp: 1}
    #pid: {p: 50.0, i: 0.1, d: 0.0}